spring:
  application:
    name: catalog
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
  servlet:
    context-path: /catalog/
resilience4j:
  circuitbreaker:
    instances:
      movie:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCalssInHalfOpenState: 5
        automaticTransitionFromOpenToHalfIfOpenEnabled: true
  retry:
    instances:
      movie:
        maxAttempts: 5
        waitDuration: 1000
        retryExceptions:
          - feign.FeignException$InternalServerError
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: MovieQueue

message: Catalog up

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: catalog microservice
  svc:
    #    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}