version: '3.2'

services:
  zipkin-service:
    image: openzipkin/zipkin:2
    container_name: zipkin-service
    restart: always
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  serie_mongo:
    image: mongo
    container_name: mongo_serie
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONG_INITDB_DATABASE=example
    ports:
      - "27016:27017"
    expose:
      - '27016'

  catalog_mongo:
    image: mongo
    container_name: mongo_catalog
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONG_INITDB_DATABASE=example
    ports:
      - "27018:27019"
    expose:
      - '27018'

#  movie_db:
#    image: woahbase/alpine-mysql
#    container_name: movie_db
#    restart: always
#    environment:
#      MYSQL_USER: 'movie_user'
#      MYSQL_USER_PWD: '1234'
#      MYSQL_USER_DB: 'movie_db'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    volumes:
#      - ./movie_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  eureka-service:
    build: eureka-service
    container_name: eureka-service
    restart: always
    depends_on:
      - zipkin-service
      - rabbitmq
    ports:
      - "8761:8761"

  config-server:
    build: server-config
    container_name: config-server
    restart: always
    depends_on:
      - eureka-service
    ports:
      - "8888:8888"

  movie-service:
    build: movie-service
    container_name: movie-service
    restart: always
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
    depends_on:
      - config-server
#      - movie_db
      - rabbitmq
    ports:
      - "8081:8081"

  serie-service:
    build: serie-service
    container_name: serie-service
    restart: always
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
    depends_on:
      - config-server
      - serie_mongo
      - rabbitmq
    ports:
      - "8083:8083"

  catalog-service:
    build: catalog-service
    container_name: catalog-service
    restart: always
    depends_on:
      - config-server
      - catalog_mongo
      - serie-service
      - movie-service
    ports:
      - "8082:8082"

  api-gateway:
    build: api-gateway 
    container_name: api-gateway
    restart: always
    depends_on:
      - catalog-service
    ports:
      - "8080:8080"