server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/reneralmeida/cloudConfig


#Config local
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: B:\IdeaProjects\Checkpoint\configServer\src\main\resources\cloudConfig